name: proto_checks

on: [pull_request]

jobs:
  proto_checks:
    name: proto lint, breaking changes detection and generating stubs from protos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wizhi/setup-buf@v1
        with:
          version: '0.36.0'
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Installing protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - name: Fetching base branch
        run: |
          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Running linter, checking breaking changes
        run: |
          buf lint
          buf breaking --against ".git#branch=${{ github.base_ref }}"          
      - name: Installing protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
          go get google.golang.org/grpc/cmd/protoc-gen-go-grpc          
      - name: Generating protos
        run: |
          mkdir -p $GEN_OUT_DIR &&
          protoc -I=$PROTO_DIR \
          --go_out=$GEN_OUT_DIR \
          --go-grpc_out=$GEN_OUT_DIR \
          $(find $PROTO_DIR -type f -name '*.proto')      
        env:
            GEN_OUT_DIR: gen/go
            PROTO_DIR: proto