name: Publication of protos releases

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        
      - name: Installing protoc-gen-go and protoc-gen-go-grpc
        run: |
          go install github.com/golang/protobuf/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generating protos
        run: |
          mkdir -p $GEN_OUT_DIR &&
          protoc -I=$PROTO_DIR \
          --go_out=$GEN_OUT_DIR \
          --go-grpc_out=$GEN_OUT_DIR \
          $(find $PROTO_DIR -type f -name '*.proto')

      - name: Compress Generated Files into Archive
        run: |
          zip -r generated-proto.${{github.ref}}.zip $GEN_OUT_DIR

      - name: Upload Generated Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-proto
          path: generated-proto.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref_name, 'refs/tags/')
        with:
          files: generated-proto.${{github.ref_name}}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    env:
      GEN_OUT_DIR: gen/go
      PROTO_DIR: proto
