name: Publication of protos releases

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install protoc-gen-go
        run: go get github.com/golang/protobuf/protoc-gen-go
      - name: Install protoc-gen-go-grpc
        run: go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Release protos
        run: |
          protoc -I=$PROTO_DIR \
          --go_out=$GEN_OUT_DIR \
          $(find $PROTO_DIR -type f -name '*.proto')
        env:
          GEN_OUT_DIR: contracts/build/go
          PROTO_DIR: contracts/proto
    env:
      GO_VERSION: '1.23.1'
      BUF_VERSION: '0.56.0'
